version: "3"

tasks:
  run:
    aliases: [url-sh]
    desc: "run url-shortner project"
    cmds:
      - go run ./cmd/url-shortner/main.go
  migrate:
    cmds:
      - go run ./cmd/migrator/main.go --up
  migrate-down:
    cmds:
      - go run ./cmd/migrator/main.go --down
  migrate-force:
    cmds:
      - go run ./cmd/migrator/main.go --force 0
  migrate-version:
    cmds:
      - go run ./cmd/migrator/main.go --version
